development:
  adapter: mongo
  database: rubystore-development
  pool: 5
  timeout: 5000

test:
  adapter: mongo
  database: rubystore-test
  pool: 5
  timeout: 5000

production:
  adapter: mongo
  database: rubystore-production
  pool: 5
  timeout: 5000
